clean_blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url

from main import views


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^contact/$', views.ContactView.as_view(), name="contact"),
    url(r'^contact-form-success/$', views.ContactFormSuccessView.as_view(), name="contact_form_success"),
    url(r'^post/(?P<pk>[\d]+)/(?P<slug>[-\w]+)/$', views.BlogDetailView.as_view(), name="post"),
]

main/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify


class CreatedUpdated(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Blog(CreatedUpdated):
    title = models.CharField(max_length=100)
    body = models.TextField()
    image = models.ImageField(upload_to="blog_images/%Y/%m/%d/")
    live = models.BooleanField(default=False)
    category = models.ManyToManyField("main.Category")

    class Meta:
        ordering = ['-modified_date']

    def __unicode__(self):
        return '%s' % self.title

    @property
    def slug(self):
        return slugify(self.title)

    def get_absolute_url(self):
        return reverse("main:post", args=[str(self.id), self.slug])


class Category(CreatedUpdated):
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" % self.title

    @property
    def slug(self):
        return slugify(self.title)

main/forms.py
from django import forms
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


class ContactForm(forms.Form):
    name = forms.CharField(max_length=120)
    email = forms.EmailField(max_length=254, min_length=6)
    message = forms.CharField(widget=forms.Textarea)

    def send_confirmation(self):
        email = EmailMessage(
            subject='Your message has been sent.',
            body=render_to_string(
                'main/email/contact_confirmation.txt', 
                {'name': self.cleaned_data['name']}
            ),
            from_email=settings.SERVER_EMAIL,
            to=[self.cleaned_data['email'],]
        )
        email.send()

    def send_email(self):
        email = EmailMessage(
            subject='Contact Form Submission',
            body=render_to_string(
                'main/email/contact_form_email.txt', {
                    'name': self.cleaned_data['name'], 
                    'email': self.cleaned_data['email'], 
                    'message': self.cleaned_data['message']
                }
            ),
            from_email=settings.SERVER_EMAIL,
            to=[settings.SERVER_EMAIL,],
            reply_to=[self.cleaned_data['email']]
        )
        email.send()

main/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from .forms import ContactForm
from .models import Blog


class AboutView(TemplateView):
    template_name = "main/about.html"


class BlogDetailView(DetailView):
    model = Blog
    template_name = "main/post.html"


class ContactFormSuccessView(TemplateView):
    template_name = "main/contact-form-success.html"


class ContactView(FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("main:contact_form_success")

    def form_valid(self, form):
        form.send_email()
        form.send_confirmation()
        return super(ContactView, self).form_valid(form)


class HomeView(ListView):
    model = Blog
    template_name = "main/home.html"
    paginate_by = 5

    def get_queryset(self):
        queryset = super(HomeView, self).get_queryset()
        return queryset.filter(live=True)

main/templates/main/_base.html
{% load google_analytics staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TW Blog{% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'main/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'main/css/clean-blog.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/img/favicon.ico' %}"/>

    <!-- Custom Fonts -->
    <link href="{% static 'main/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% if not debug %}
    {% google_analytics %}
    {% endif %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="https://www.trevorwatson.info/">Trevor Watson</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'main:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'main:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% block header_image %}{% endblock %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {% block header %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    {% block content %}
    {% endblock %}

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/cfc603" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/trevor.watson.33" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/watsontrevor/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/cfc603" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Trevor Watson {% now "Y" %}</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'main/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'main/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'main/js/clean-blog.min.js' %}"></script>

    <!-- Page Level JavaScript -->
    {% block page_js %}
    {% endblock %}

</body>

</html>

main/templates/main/about.html
{% extends "main/_base.html" %}
{% load staticfiles %}

<!-- Head -->
{% block title %} - About{% endblock %}

<!-- body -->

<!-- Header -->
{% block header_image %}{% static 'main/img/about-bg.jpg' %}{% endblock %}

{% block header %}
<div class="page-heading">
    <h1>About Me</h1>
    <hr class="small">
    <span class="subheading">This is what I do.</span>
</div>
{% endblock %}


<!-- Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/contact-form-success.html
{% extends "main/_base.html" %}
{% load staticfiles %}

<!-- Head -->
{% block title %}Clean Blog - Contact{% endblock %}

<!-- body -->

<!-- Header -->
{% block header_image %}{% static 'main/img/contact-bg.jpg' %}{% endblock %}

{% block header %}
<div class="page-heading">
    <h1>Contact Me</h1>
    <hr class="small">
    <span class="subheading">Have questions? I have answers (maybe).</span>
</div>
{% endblock %}


<!-- Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Your request has been submitted. We will be in contact soon.</p>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/contact.html
{% extends "main/_base.html" %}
{% load staticfiles bootstrap_tags %}

<!-- Head -->
{% block title %} - Contact{% endblock %}

<!-- body -->

<!-- Header -->
{% block header_image %}{% static 'main/img/contact-bg.jpg' %}{% endblock %}

{% block header %}
<div class="page-heading">
    <h1>Contact Me</h1>
</div>
{% endblock %}


<!-- Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Want to get in touch with me? Fill out the form below to send me a message.</p>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <button type="submit" class="btn btn-default">Send Message</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends "main/_base.html" %}
{% load staticfiles %}

<!-- body -->

<!-- Header -->
{% block header_image %}{% static 'main/img/home-bg.jpg' %}{% endblock %}

{% block header %}
<div class="site-heading">
    <h1>Trevor Watson</h1>
    <hr class="small">
    <span class="subheading">A Technical Blog</span>
</div>
{% endblock %}


<!-- Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for post in object_list %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {% autoescape off %}
                            {{ post.body|truncatewords_html:15}}
                        {% endautoescape %}
                    </h3>
                </a>
                <p class="post-meta">Posted by <a href="{% url 'main:about' %}">Trevor Watson</a> on {{ post.modified_date|date:"N j, Y" }}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- Pager -->
            <ul class="pager">
            {% if page_obj.has_previous %}
                <li class="previous">
                    <a href="?page={{ page_obj.previous_page_number }}">Newer Posts &larr;</a>
                </li>
            {% endif %}
            {% if page_obj.paginator.num_pages > 1 %}
                <li>
                    <span>
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="next">
                    <a href="?page={{ page_obj.next_page_number }}">Older Posts &rarr;</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/post.html
{% extends "main/_base.html" %}
{% load staticfiles %}

<!-- Head -->
{% block title %} - {{ object.title }}{% endblock %}

<!-- body -->

<!-- Header -->
{% block header_image %}{{ MEDIA_URL }}{{ object.image }}{% endblock %}

{% block header %}
<div class="post-heading">
    <h1>{{ object.title }}</h1>
    <h2 class="subheading">
        {% autoescape off %}
            {{ object.body|truncatewords_html:15 }}
        {% endautoescape %}
    </h2>
    <span class="meta">Posted by <a href="{% url 'main:about' %}">Trevor Watson</a> on {{ object.modified_date|date:"N j, Y" }}</span>
</div>
{% endblock %}


<!-- Content -->
{% block content %}
<article>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
            {% autoescape off %}
                {{ object.body }}
            {% endautoescape %}
            </div>
        </div>
    </div>
</article>
{% endblock %}

{% block page_js %}
<!-- SyntaxHighlighter -->

<!-- Main JavaScript File -->
<script type="text/javascript" src="{% static 'main/vendor/syntaxhighlighter/js/shCore.js' %}"></script>
 
<!-- Brushes -->
<script type="text/javascript" src="{% static 'main/vendor/syntaxhighlighter/js/shBrushPython.js' %}"></script>
<script type="text/javascript" src="{% static 'main/vendor/syntaxhighlighter/js/shBrushXml.js' %}"></script>
 
<!-- Styling -->
<link href="{% static 'main/vendor/syntaxhighlighter/css/shCoreRDark.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'main/vendor/syntaxhighlighter/css/shThemeRDark.css' %}" rel="stylesheet" type="text/css" />
 
<!-- Run the highlighter -->
<script type="text/javascript">
     SyntaxHighlighter.all()
</script>

<!-- End SyntaxHighlighter -->
{% endblock %}